CREATE DATABASE IF NOT EXISTS
    GDPR CHARACTER SET utf8mb4;
CREATE USER IF NOT EXISTS
    'netsec'@localhost IDENTIFIED BY '27808d983c4e2e6a47fb049c';
GRANT ALL PRIVILEGES ON GDPR.* TO netsec@localhost;
FLUSH PRIVILEGES;
